-- 1. Display Orders Issued by Salesman 'Paul Adam'
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE salesman_id = (SELECT salesman_id FROM Salesman WHERE name = 'Paul Adam');

-- 2. Display Orders Generated by London-Based Salespeople
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE salesman_id IN (SELECT salesman_id FROM Salesman WHERE city = 'London');

-- 3. Display Orders from Salespeople Handling Customer ID 3007
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE salesman_id IN (SELECT salesman_id FROM Customer WHERE customer_id = 3007);

-- 4. Display Orders Exceeding Average Value on 10-Oct-2012
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE purch_amt > (SELECT AVG(purch_amt) FROM Orders WHERE ord_date = '2012-10-10');

-- 5. Display Orders Generated in New York City
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE salesman_id IN (SELECT salesman_id FROM Salesman WHERE city = 'New York');

-- 6. Display Commission of Salespeople in Paris
SELECT commission 
FROM Salesman 
WHERE city = 'Paris';

-- 7. Display Customers with ID Below 2001 Under Salesperson Mc Lyon
SELECT * 
FROM Customer 
WHERE salesman_id = (SELECT salesman_id FROM Salesman WHERE name = 'Mc Lyon') 
AND customer_id < 2001;

-- 8. Count of Customers with Above-Average Grades in New York City
SELECT grade, COUNT(*) AS customer_count 
FROM Customer 
WHERE city = 'New York' AND grade > (SELECT AVG(grade) FROM Customer)
GROUP BY grade;

-- 9. Display Orders of Salespeople with Maximum Commission
SELECT ord_no, purch_amt, ord_date, salesman_id 
FROM Orders 
WHERE salesman_id IN (SELECT salesman_id FROM Salesman WHERE commission = (SELECT MAX(commission) FROM Salesman));

-- 10. Display Customers Who Placed Orders on 17th August 2012
SELECT o.ord_no, o.purch_amt, o.ord_date, o.customer_id, o.salesman_id, c.cust_name 
FROM Orders o 
JOIN Customer c ON o.customer_id = c.customer_id 
WHERE o.ord_date = '2012-08-17';

-- 11. Display Orders Placed by Customers with the Highest Grade
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE customer_id IN (SELECT customer_id FROM Customer WHERE grade = (SELECT MAX(grade) FROM Customer));

-- 12. Display Orders Where the Salesperson Earned More Than 5% Commission
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE salesman_id IN (SELECT salesman_id FROM Salesman WHERE commission > 0.05);

-- 13. Display Salespeople Who Did Not Generate Any Orders
SELECT name FROM Salesman 
WHERE salesman_id NOT IN (SELECT DISTINCT salesman_id FROM Orders);

-- 14. Display Customers Who Have Not Placed Any Orders
SELECT cust_name FROM Customer 
WHERE customer_id NOT IN (SELECT DISTINCT customer_id FROM Orders);

-- 15. Display Orders Where Purchase Amount is Above the Average of All Orders
SELECT ord_no, purch_amt, ord_date, customer_id, salesman_id 
FROM Orders 
WHERE purch_amt > (SELECT AVG(purch_amt) FROM Orders);

-- 16. Display Salespeople Who Handle More Than 3 Customers
SELECT salesman_id, name 
FROM Salesman 
WHERE salesman_id IN (
    SELECT salesman_id 
    FROM Customer 
    GROUP BY salesman_id 
    HAVING COUNT(customer_id) > 3
);

-- 17. Display Customers Who Have Placed Orders of More Than $1000
SELECT DISTINCT customer_id, cust_name 
FROM Customer 
WHERE customer_id IN (SELECT customer_id FROM Orders WHERE purch_amt > 1000);

-- 18. Display the Highest Purchase Amount and the Corresponding Order Details
SELECT * 
FROM Orders 
WHERE purch_amt = (SELECT MAX(purch_amt) FROM Orders);

-- 19. Display Customers with the Same Grade as "John Smith"
SELECT * 
FROM Customer 
WHERE grade = (SELECT grade FROM Customer WHERE cust_name = 'John Smith');

-- 20. Display Orders with a Purchase Amount in the Top 10% of All Orders
SELECT * 
FROM Orders 
WHERE purch_amt >= (SELECT PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY purch_amt) FROM Orders);

-- 21. Display the Oldest Order in the Database
SELECT * FROM Orders 
WHERE ord_date = (SELECT MIN(ord_date) FROM Orders);

-- 22. Display Customers Who Are Handled by Salespeople in 'New York'
SELECT * 
FROM Customer 
WHERE salesman_id IN (SELECT salesman_id FROM Salesman WHERE city = 'New York');

-- 23. Display Orders Where the Customer Grade is Below the Average Grade
SELECT * FROM Orders 
WHERE customer_id IN (
    SELECT customer_id FROM Customer WHERE grade < (SELECT AVG(grade) FROM Customer)
);

-- 24. Display Customers Who Share the Same City as the Salesperson Handling Them
SELECT * 
FROM Customer c
JOIN Salesman s ON c.salesman_id = s.salesman_id 
WHERE c.city = s.city;

-- 25. Display Salespeople Who Have Earned the Maximum Commission in a City
SELECT name, city, commission 
FROM Salesman 
WHERE commission = (SELECT MAX(commission) FROM Salesman WHERE city = Salesman.city);

-- 26. Display Orders of Salespeople Who Have a Commission Higher Than the Company Average
SELECT * 
FROM Orders 
WHERE salesman_id IN (SELECT salesman_id FROM Salesman WHERE commission > (SELECT AVG(commission) FROM Salesman));

-- 27. Display Orders Issued in the Last 6 Months
SELECT * FROM Orders 
WHERE ord_date >= DATEADD(MONTH, -6, GETDATE());

-- 28. Display the Most Recent Order for Each Salesperson
SELECT * FROM Orders o1 
WHERE ord_date = (SELECT MAX(ord_date) FROM Orders o2 WHERE o1.salesman_id = o2.salesman_id);

-- 29. Display Orders Where the Customer ID Matches a Salesman ID
SELECT * FROM Orders 
WHERE customer_id IN (SELECT salesman_id FROM Salesman);

-- 30. Display Customers Who Have the Same Grade as Their Salesperson’s Commission Percentage
SELECT * FROM Customer 
WHERE grade = (SELECT commission * 100 FROM Salesman WHERE salesman_id = Customer.salesman_id);

-- 31. Display Salespeople Who Handle Only One Customer
SELECT * FROM Salesman 
WHERE salesman_id IN (
    SELECT salesman_id FROM Customer GROUP BY salesman_id HAVING COUNT(customer_id) = 1
);

-- 32. Display the Sum of All Orders Placed in Each City
SELECT city, SUM(purch_amt) AS total_sales 
FROM Customer c 
JOIN Orders o ON c.customer_id = o.customer_id 
GROUP BY city;

-- 33. Display the Average Purchase Amount of Orders for Each City
SELECT city, AVG(purch_amt) AS avg_sales 
FROM Customer c 
JOIN Orders o ON c.customer_id = o.customer_id 
GROUP BY city;

-- 34. Display Customers Whose First Name Starts with 'A'
SELECT * FROM Customer WHERE cust_name LIKE 'A%';

-- 35. Display Orders Where the Purchase Amount is a Multiple of 100
SELECT * FROM Orders WHERE purch_amt % 100 = 0;

-- 36. Display Customers Who Have Placed Exactly 2 Orders
SELECT customer_id, COUNT(ord_no) AS order_count 
FROM Orders 
GROUP BY customer_id 
HAVING COUNT(ord_no) = 2;

-- 37. Display the Number of Orders Placed by Each Customer
SELECT customer_id, COUNT(ord_no) AS order_count 
FROM Orders 
GROUP BY customer_id;

-- 38. Display the Total Purchase Amount for Each Salesperson
SELECT salesman_id, SUM(purch_amt) AS total_sales 
FROM Orders 
GROUP BY salesman_id;

-- 39. Display the Name of Salespeople Who Earn the Highest Commission in Their City
SELECT name, city, commission 
FROM Salesman s1 
WHERE commission = (SELECT MAX(commission) FROM Salesman s2 WHERE s1.city = s2.city);
