USE TechShop;

-- 1. Find out which customers have not placed any orders
SELECT c.FirstName, c.LastName
FROM Customers c
LEFT JOIN Orders o ON c.CustomerID = o.CustomerID
WHERE o.CustomerID IS NULL;

-- 2. Find the total number of products available for sale
SELECT COALESCE(SUM(i.QuantityInStock), 0) AS TotalProductsAvailable
FROM Inventory i
LEFT JOIN Products p ON i.ProductID = p.ProductID;


-- 3. Calculate the total revenue generated by TechShop
SELECT SUM(o.TotalAmount) AS TotalRevenue
FROM Orders o;

-- 4. Calculate the average quantity ordered for a specific product
-- Replace 'Laptop' with an actual product name when querying
SELECT AVG(od.Quantity) AS AvgQuantityOrdered
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
WHERE p.ProductName = 'Laptop';

-- 5. Calculate the total revenue generated by a specific customer
-- Replace 5 with an actual CustomerID when querying
SELECT SUM(o.TotalAmount) AS TotalRevenue
FROM Orders o
WHERE o.CustomerID = 5;

-- 6. Find the customer who has placed the most orders
SELECT TOP 1 c.FirstName, c.LastName, COUNT(o.OrderID) AS NumOrders
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.FirstName, c.LastName
ORDER BY NumOrders DESC;

-- 7. Find the most popular product based on total quantity ordered
SELECT TOP 1 p.ProductName, SUM(od.Quantity) AS TotalQuantityOrdered
FROM OrderDetails od
JOIN Products p ON od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY TotalQuantityOrdered DESC;

-- 8. Find the customer who has spent the most money on products
SELECT TOP 1 c.FirstName, c.LastName, SUM(o.TotalAmount) AS TotalSpending
FROM Orders o
JOIN Customers c ON o.CustomerID = c.CustomerID
GROUP BY c.CustomerID, c.FirstName, c.LastName
ORDER BY TotalSpending DESC;

-- 9. Calculate the average order value for all customers
SELECT c.FirstName, c.LastName, AVG(o.TotalAmount) AS AvgOrderValue
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.FirstName, c.LastName;

-- 10. Find the total number of orders placed by each customer
SELECT c.FirstName, c.LastName, COUNT(o.OrderID) AS NumOrders
FROM Customers c
JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.FirstName, c.LastName;
